name: net_runner
description: "Client for scan local network"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0
  path_provider: ^2.0.11
  csslib: ^1.0.2
  loading_animation_widget: ^1.3.0
  flutter_slider_drawer: ^2.1.3
  flutter_zoom_drawer: ^3.2.0
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.xml

