name: net_runner
description: "Client for scan local network"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0
  path_provider: ^2.0.11
  csslib: ^1.0.2
  loading_animation_widget: ^1.3.0
  flutter_slider_drawer: ^2.1.3
  flutter_zoom_drawer: ^3.2.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.1.2
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  #logging: ^1.3.0
  flutter_cache_manager: ^3.4.1
  universal_platform: ^1.1.0
  platform_detector: ^0.2.0
  logger: ^2.5.0
  http: ^1.2.2
  bloc: ^8.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: enable
  uses-material-design: true
  assets:
    - assets/data.xml

